### PR TITLE
[travis] fixed php memory limit issues

### PR DESCRIPTION
**Pull request by bdunogier**
Disabled xdebug and memory limit when running composer.

### CODE REVIEW

**Comment by andrerom** [comment]
https://github.com/ezsystems/LegacyBridge/commit/d2c5534fad165e5095a8b16f081ed2bd36bf5c4b

**Comment by bdunogier** [comment]
Thank you @andrerom, I'll look into it if what I have just pushed fails as well.

**Comment by bdunogier** [comment]
Okay, memory issues are gone. We have failures now :-)

**Comment by bdunogier** [comment]
+1 for merging it, even if it fails ? It's still an improvement over the current {{master}}.

**Comment by andrerom** [comment]
+1

**Pull request merged**
