### PR TITLE
Implement EZP-24804: Ancestor criterion

### PR DESCRIPTION
**Pull request by pspanja**
This PR resolves https://jira.ez.no/browse/EZP-24804
Review together with https://github.com/ezsystems/ezpublish-kernel/pull/1409

This implements `Ancestor` criterion visitors, accepting Location path string(s) as value.

### CODE REVIEW

**Comment by andrerom** [comment]
in support seems to be missing, should we skip it form api if we don't intend to impl it anytime soon?

**Comment by pspanja** [comment]
`IN` is already handled in the same visitor, but `canVisit()` was allowing `EQ` only.
Now updated and rebased.

**Comment by andrerom** [comment]
+1

**Comment by lolautruche** [comment]
+1

**Pull request merged**
