### PR TITLE
IBX-3116: Made Section identifier nonconvertible

### PR DESCRIPTION
**Pull request by barw4**
| Question                                  | Answer
| ----------------------------------------- | ------------------
| **JIRA issue**                            | [IBX-3116](https://issues.ibexa.co/browse/IBX-3116)
| **Type**                                  | bug
| **Target Ibexa DXP version**              | `v3.3`
| **BC breaks**                             | no

As the title suggests.

### CODE REVIEW

**Review by adamwojs — CHANGES_REQUESTED** [review]
Are you sure you know what you are doing?

Instead of changing type to string please use raw flag on identifier field type or change string normalization in a way to that underscores will be accepted. 

Please note that similar changes need to be applied for elasticsearch integration and integration test is mandatory in this case.

**Comment by barw4** [comment]
@adamwojs yes, I'm sure. I was thinking about changing converter to accept "-", but that drastically changes schema in other places.

Besides, we do have strings here as well: https://github.com/ezsystems/ezplatform-solr-search-engine/blob/9d665367d9e6599b395efb721ea3ddbbdc91cef5/lib/FieldMapper/ContentFieldMapper/BlockDocumentsBaseContentFields.php#L187-L190 - those are also identifiers?

**Review by adamwojs — APPROVED** [review]

**Review by Steveb-p — APPROVED** [review]
Please be aware that in cases like this describing what the PR contents are does not describe **why** are they necessary.

**Review by bogusez — APPROVED** [review]

**Comment by adamwojs** [comment]
Could you please merge up changes?

**Pull request merged**
