### PR TITLE
EZP-31113: Configured Slot for AssignSectionToSubtreeSignal

### PR DESCRIPTION
**Pull request by kmadejski**
This PR depends on: https://github.com/ezsystems/ezpublish-kernel/pull/2862. Please refer to it for more information.

### CODE REVIEW

**Comment by andrerom** [comment]
> but should cherry pick this one here as well: 436fedc

ignore, this is not a hard dependency in this case 👍

**Comment by kmadejski** [comment]
Tests are failing because depend on `ezpublish-kernel` PR.

**Comment by kmadejski** [comment]
@alongosz done in https://github.com/ezsystems/ezplatform-solr-search-engine/pull/160/commits/e6239a9360ec3a6a66a22cbb731f0b0e529d991d.

**Comment by andrerom** [comment]
@adamwojs Failure seems to be comming from 1.7 branch: https://travis-ci.org/ezsystems/ezplatform-solr-search-engine/branches?utm_medium=notification&utm_source=github_status

ref:
```
1) eZ\Publish\API\Repository\Tests\SearchServiceTranslationLanguageFallbackTest::testFindContent with data set #0 (array(array('eng-GB', 'ger-DE', 'por-PT'), false), array(array(1, 'eng-GB', array('localhost:8983/solr/core0', 'localhost:8983/solr/core3', 'localhost:8983/solr/collection1', 'http://localhost:8983/solr/co...ca_n1/')), array(2, 'ger-DE', array('localhost:8983/solr/core3', 'localhost:8983/solr/core2', 'localhost:8983/solr/collection1', 'http://localhost:8983/solr/co...ca_n1/')), array(3, 'por-PT', array('localhost:8983/solr/core2', 'localhost:8983/solr/core2', 'localhost:8983/solr/collection1', 'http://localhost:8983/solr/co...ca_n1/'))))
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'http://localhost:8983/solr/core0_shard1_replica_n1/'
+'http://localhost:8983/solr/core0_shard1_replica1/'
```

**Comment by andrerom** [comment]
Passing now, thanks @adamwojs!
Merging and stripping on merge to master.

**Pull request merged**
