### PR TITLE
Fix EZP-25334: Missing PermissionSubtree Criterion Visitor

### PR DESCRIPTION
**Pull request by harmstyler**
PermissionVisitor was not implemented yet, this causes an uncaught exception when controlling user permissions by subtree.

### CODE REVIEW

**Comment by andrerom** [comment]
I guess you just copied SubtreeVisitor here?

I would rather fix this in Core actually *(Making PermissionSubtree extend Subtree, and making sure Legacy Engine, which has this issue, picks the enhanced one)*.

**Comment by harmstyler** [comment]
I'm not sure what `SubtreeVisitor` is, maybe `SubtreeIn`? My PR just adds another visitor for when `$criterion` of class `eZ\Publish\Core\Repository\Values\Content\Query\Criterion\PermissionSubtree` is passed.

It would make sense to fix in core if Core and reuse what's already there. Any chance that fix would make it into the 5.4.x releases?

**Comment by andrerom** [comment]
> It would make sense to fix in core and reuse what's already there. Any chance that fix would make it into the 5.4.x releases?

sure, but we

**Comment by pspanja** [comment]
I think this can be best fixed on the Legacy Search Engine side, as @andrerom suggested.
See https://github.com/ezsystems/ezpublish-kernel/pull/912#discussion_r49459938.

**Comment by andrerom** [comment]
PR created, review and testing more then welcome :)
 https://github.com/ezsystems/ezpublish-kernel/pull/1562

**Pull request closed without merging**
