### PR TITLE
EZP-25788: Solr not indexing on content publish

### PR DESCRIPTION
**Pull request by janit**
Added comment about commit and softcommit configurations in Solr.

### CODE REVIEW

**Comment by andrerom** [comment]
@janit If you agree I think we can do better, could you add something like the following as well:
```
Example of working `solrconfig.xml` settings that you can use to tune for your needs *(changes here: enables `openSearcher` and changes AutoSoftCommit from `-1` disabled to `50`ms)*:

         <autoCommit> 
           <maxTime>${solr.autoCommit.maxTime:15000}</maxTime> 
           <openSearcher>true</openSearcher> 
         </autoCommit>

         <autoSoftCommit> 
           <maxTime>${solr.autoSoftCommit.maxTime:50}</maxTime> 
         </autoSoftCommit>
```

**Comment by andrerom** [comment]
ping @pspanja

**Comment by andrerom** [comment]
@janit discussed with @pspanja, and seems we don't need openSearcher, if softCommit is done, so updated comment above.

**Comment by andrerom** [comment]
+1

**Comment by pspanja** [comment]
+1

**Pull request merged**
