### PR TITLE
EZP-26756: FieldRelation location criterion visitor

### PR DESCRIPTION
**Pull request by florianalexandre**
JIRA issue: https://jira.ez.no/browse/EZP-26756

Allow the use of FieldRelation criterion in location queries
Use existing FieldRelation content criterion visitor

### CODE REVIEW

**Comment by andrerom** [comment]
Thanks for the contribution so far, hopefully we'll get around to have a look at this next week when @pspanja is back to give you some review feedback :)

**Comment by pspanja** [comment]
This looks good, but we should also have integration tests for it in https://github.com/ezsystems/ezpublish-kernel.
We already have tests for `FieldRelation` with Content search, they would only need to be adapted to work for Location search as well, in the same style as we already do with other tests.

@florianalexandre let me know if you are up for this.

We'll need an issue as well :)

**Comment by andrerom** [comment]
Status for those wondering _(including myself)_:
- [x] visitor _(fixed in master, aka 1.2.x already)_
- [ ] integration test on kernel
- [ ] jira issue

**Comment by pspanja** [comment]
I'm taking this over, thanks for the contribution @florianalexandre!
Continued in https://github.com/ezsystems/ezplatform-solr-search-engine/pull/80, the commit is preserved there.

**Pull request closed without merging**
