### PR TITLE
EZP-24649: Solr: Index Locations as nested documents of Content

### PR DESCRIPTION
**Pull request by pspanja**
This PR resolves https://jira.ez.no/browse/EZP-24649
See also: https://github.com/ezsystems/ezpublish-kernel/pull/1358

This implements indexing of Location documents as nested (block joined) documents of Content.
With that change the semantic configuration is simplified, and Location index is no longer separately configured.

### Reasoning

Currently we don't support fulltext search with Location Search. Having Locations as nested documents of Content will enables us implementation of fulltext Location search using block join, for example:

```
{!child of=document_type_id:content v='<fulltext condition>'}
```

That means we don't have to include fulltext field in the Location documents, but can refer to the one in the (parent) Content document. Avoiding that means having better relevancy calculation.

However, since it is not possible to sort and facet using block join, we still must index **all** Content fields in the Location document, same as in the Content document. These will be typically analyzed as keywords and will skew statistics in some measure.

### CODE REVIEW

**Comment by andrerom** [comment]
+1

**Comment by pspanja** [comment]
Ready for review, ping @andrerom @paulborgermans 

Note the description regarding indexing Content fields and skewing of relevancy, I don't know how much of a problem this can be in the practice and if it is acceptable or not.

**Comment by bdunogier** [comment]
> Note the description regarding indexing Content fields and skewing of relevancy, I don't know how much of a problem this can be in the practice and if it is acceptable or not.

I think it is acceptable, even though I might change my mind depending on the concrete consequences on actual use-cases.

But we must document this as a known issue/thing/feature.

**Comment by andrerom** [comment]
> However, since it is not possible to sort and facet using block join, we still must index all Content fields in the Location document, same as in the Content document. These will be typically analyzed as keywords and will skew statistics in some measure.

But since we can decide to only use it for sorting we can for instance index a subset now right? At least as long as Field SortClause is not supporting custom fields for instance.

**Comment by andrerom** [comment]
+1

**Comment by pspanja** [comment]
Thanks for the reviews!

**Pull request merged**
